project:
  type: website

website:
  title: "Karen Myna Cantor - YA Author"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: books.qmd
        text: Books
      - href: media_kit.qmd
        text: Media Kit
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual